In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print( torch.__version__)

2.2.2+cu121


In [ ]:
!nvidia-smi

## Introdcution to Tensors

### Creating tensors

In [3]:
# scalar
scaler = torch.tensor( 7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# get tensor back as python int
scaler.item()

7

In [6]:
vector = torch.tensor( [ 7, 7])

vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor( [
	[ 7, 8],
	[ 9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[ 0], MATRIX[ 1]

(tensor([7, 8]), tensor([ 9, 10]))

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor( [ [
	[ 1, 2, 3],
	[ 3, 6, 9],
	[ 2, 4, 5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[ 0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [17]:
# Create a random tensor of size ( 3, 4)
random_tensor = torch.rand( 3, 4)

random_tensor

tensor([[0.5583, 0.5652, 0.1884, 0.4073],
        [0.1561, 0.7406, 0.0514, 0.8122],
        [0.8424, 0.0152, 0.3389, 0.1498]])

In [18]:
random_tensor.ndim

2

In [19]:
# create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand( size=( 224, 224, 3))

In [20]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and Ones

In [21]:
zeros = torch.zeros( size=( 3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones( size=( 3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
range_tensor = torch.arange( start=0, end=1000, step=77)

range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Create tensors like

zeros_like_range_tensor = torch.zeros_like( input=range_tensor)

zeros_like_range_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [27]:
float_32_tensor = torch.tensor(
	[ 3.0, 6.0, 9.0],
	dtype=None,				# what datatype is the tensor
	device=None,			# what device is your tensor on
	requires_grad=False		# whether or not to track gradient with this tensor operations
)

In [28]:
float_16_tensor = float_32_tensor.type( torch.float16)

float_16_tensor.dtype

torch.float16

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = float_32_tensor.type( torch.int32)

In [31]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Get information from tensors

In [32]:
some_tensor = torch.rand( 3, 4)

some_tensor

tensor([[0.6260, 0.7409, 0.4300, 0.6758],
        [0.6843, 0.8383, 0.7109, 0.0891],
        [0.8354, 0.8407, 0.0546, 0.8057]])

In [33]:
print( some_tensor)
print( f"Datatype of tensor: { some_tensor.dtype}")
print( f"Shape of tensor: { some_tensor.shape}")
print( f"Device of tensor: { some_tensor.device}")

tensor([[0.6260, 0.7409, 0.4300, 0.6758],
        [0.6843, 0.8383, 0.7109, 0.0891],
        [0.8354, 0.8407, 0.0546, 0.8057]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

In [34]:
# create a tensor

tensor = torch.tensor( [ 1, 2, 3])

tensor

tensor([1, 2, 3])

In [35]:
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
torch.mul( tensor, 10)

tensor([10, 20, 30])

In [39]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
# Element wise multiplication

tensor * tensor

tensor([1, 4, 9])

In [41]:
# Matric Multiplication

torch.matmul( tensor, tensor)

tensor(14)

In [42]:
%%time

value = 0

for i in range( len( tensor)):
	value += tensor[ i] * tensor[ i]

print( value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [43]:
%%time

torch.matmul( tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [44]:
tensor @ tensor

tensor(14)

In [45]:
torch.matmul( torch.rand( 3, 2), torch.rand( 2, 3))

tensor([[0.6215, 0.6940, 0.7575],
        [0.2060, 0.5414, 0.7632],
        [0.5378, 0.6513, 0.7388]])

In [46]:
tensor_A = torch.tensor([
	[ 1, 2],
	[ 3, 4],
	[ 5, 6]
])

tensor_B = torch.tensor( [
	[ 7, 10],
	[ 8, 11],
	[ 9, 12]
])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [47]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [48]:
tensor_B.T.shape

torch.Size([2, 3])

In [49]:
torch.matmul( tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tenosr aggregation)

In [50]:
# Create a tensor

x = torch.arange( 0, 100, 10)

x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
torch.min( x), x.min()

(tensor(0), tensor(0))

In [52]:
torch.max( x), x.max()

(tensor(90), tensor(90))

In [53]:
torch.mean( x.type( torch.float32)), x.type( torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
torch.sum( x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [55]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [56]:
x[ 0], x[ 9]

(tensor(0), tensor(90))

### Reshaping, stacking, sqeezing and unsqueezing tensors

In [57]:
x = torch.arange( 1., 10.)

x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [58]:
x_reshaped = x.reshape( 9, 1)

x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
z = x.view( 1, 9)	# views share the same memory

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
z[:, 0] = 0

z, x

(tensor([[0., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([0., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
x_stacked = torch.stack( [ x, x, x, x], dim=1)

x_stacked

tensor([[0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [62]:
x_reshaped.shape

torch.Size([9, 1])

In [63]:
x_squeezed = x_reshaped.squeeze()

x_squeezed, x_squeezed.shape

(tensor([0., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
x_unsqueezed = x_squeezed.unsqueeze( dim=1)

x_unsqueezed, x_unsqueezed.shape

(tensor([[0.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [65]:
x_original = torch.rand( size=( 224, 224, 3))

x_permuted = x_original.permute( 2, 0, 1) # shares the memeory

x_permuted.shape

torch.Size([3, 224, 224])

In [66]:
x_original[ 0, 0, 0] = 0

x_original[ 0, 0, 0], x_permuted[ 0, 0, 0]

(tensor(0.), tensor(0.))

### Indexing

In [67]:
x = torch.arange( 1, 10).reshape( 1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [68]:
x[ 0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[ 0, 0], x[ 0][ 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [70]:
x[ 0, 0, 0], x[ 0][ 0][ 0]

(tensor(1), tensor(1))

In [71]:
x[ :, 0]

tensor([[1, 2, 3]])

In [72]:
x[ :, :, 1]

tensor([[2, 5, 8]])

In [73]:
x[ :, 1, 1]

tensor([5])

In [74]:
x[ 0, 0, :]

tensor([1, 2, 3])

In [75]:
x[ :, :, 2], x[ 0, :, 2]

(tensor([[3, 6, 9]]), tensor([3, 6, 9]))

### tensors and ndarray

In [76]:
array = np.arange( 1.0, 8.0)

tensor = torch.from_numpy( array)	# warning pytorch reflect numpy datatype (default for numpy is float64 while for pytorch is float32)

tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.float64)

In [77]:
array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
tensor = torch.ones( 7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [79]:
tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
random_tensor_A = torch.rand( 3, 4)
random_tensor_B = torch.rand( 3, 4)

print( random_tensor_A)
print( random_tensor_B)
print( random_tensor_A == random_tensor_B)

tensor([[0.6114, 0.5536, 0.3180, 0.5827],
        [0.3946, 0.5886, 0.3336, 0.0414],
        [0.6673, 0.5296, 0.4617, 0.1599]])
tensor([[0.5265, 0.8308, 0.9960, 0.8567],
        [0.0584, 0.6259, 0.0913, 0.3206],
        [0.0647, 0.7949, 0.1578, 0.8125]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
RANDOM_SEED = 42

torch.manual_seed( RANDOM_SEED)
random_tensor_A = torch.rand( 3, 4)

torch.manual_seed( RANDOM_SEED)
random_tensor_B = torch.rand( 3, 4)

print( random_tensor_A)
print( random_tensor_B)
print( random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### GPU computation

In [82]:
torch.cuda.is_available()

True

In [83]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [84]:
torch.cuda.device_count()

1

In [85]:
tensor = torch.tensor( [ 1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [86]:
tensor_on_gpu = tensor.to( device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [87]:
# the line below won't work because numpy only works on cpu
# tensor_on_gpu.numpy()

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)