In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print( torch.__version__)

2.2.2+cu121


In [ ]:
!nvidia-smi

## Introdcution to Tensors

### Creating tensors

In [4]:
# scalar
scaler = torch.tensor( 7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
# get tensor back as python int
scaler.item()

7

In [7]:
vector = torch.tensor( [ 7, 7])

vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor( [
	[ 7, 8],
	[ 9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[ 0], MATRIX[ 1]

(tensor([7, 8]), tensor([ 9, 10]))

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor( [ [
	[ 1, 2, 3],
	[ 3, 6, 9],
	[ 2, 4, 5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[ 0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [18]:
# Create a random tensor of size ( 3, 4)
random_tensor = torch.rand( 3, 4)

random_tensor

tensor([[0.6855, 0.2721, 0.3534, 0.4799],
        [0.5359, 0.6593, 0.2524, 0.1910],
        [0.5735, 0.9653, 0.8590, 0.1524]])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand( size=( 224, 224, 3))

In [21]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and Ones

In [22]:
zeros = torch.zeros( size=( 3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones( size=( 3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
range_tensor = torch.arange( start=0, end=1000, step=77)

range_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Create tensors like

zeros_like_range_tensor = torch.zeros_like( input=range_tensor)

zeros_like_range_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [28]:
float_32_tensor = torch.tensor(
	[ 3.0, 6.0, 9.0],
	dtype=None,				# what datatype is the tensor
	device=None,			# what device is your tensor on
	requires_grad=False		# whether or not to track gradient with this tensor operations
)

In [29]:
float_16_tensor = float_32_tensor.type( torch.float16)

float_16_tensor.dtype

torch.float16

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = float_32_tensor.type( torch.int32)

In [32]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Get information from tensors

In [33]:
some_tensor = torch.rand( 3, 4)

some_tensor

tensor([[0.1436, 0.2995, 0.6209, 0.5117],
        [0.5418, 0.7662, 0.1650, 0.5517],
        [0.8552, 0.5369, 0.4572, 0.5757]])

In [34]:
print( some_tensor)
print( f"Datatype of tensor: { some_tensor.dtype}")
print( f"Shape of tensor: { some_tensor.shape}")
print( f"Device of tensor: { some_tensor.device}")

tensor([[0.1436, 0.2995, 0.6209, 0.5117],
        [0.5418, 0.7662, 0.1650, 0.5517],
        [0.8552, 0.5369, 0.4572, 0.5757]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu
